### ISSUE TITLE
Questions about group enbale

### ISSUE THREAD

**Issue by gelway** [SengerM/CAENpy#3]
Hi, I'm implementing some functionality with the API you developed. I'm using V1742, with four groups of channels, I've added two parameters to enable_channels method, the code is like below and I've set the four channels to True. however, I've output event.GrPresent[:] in the get_waveforms method, and it outputs 1,1,0,0, and only the first two groups are enabled. Is there something wrong with my writing? I would be very grateful if you could help me! Thank you very much.
	
def enable_channels(self, group_1:bool, group_2:bool,group_3:bool,group_4:bool):
		mask = 0
		for i,group in enumerate([group_1,group_2,group_3,group_4]):
			mask |= (1 if group else 0) << i
		code = libCAENDigitizer.CAEN_DGTZ_SetGroupEnableMask(
			self._get_handle(), 
			c_uint32(mask),
		)
		check_error_code(code)

**Comment by SengerM** [comment]
Hi, according to the documentation of the [CAENDigitizer library](https://www.caen.it/download/?filter=CAENDigitizer%20Library), your code should work. Note, however, that my function `get_waveforms` has hardcoded all the channels numbers for the 16 channel digitizer. If you are using a 32 channel unit, you should change this as well. This should not be too much complicated.
