### ISSUE TITLE
Add implementation for send_sw_trigger

### ISSUE THREAD

**Issue by FraH90** [SengerM/CAENpy#5]
As description, it would be usefull to add implementation for send_sw_trigger.

I've manually added this to the CAEN_DT5742_Digitizer class in my system, and it works:

`
	def send_sw_trigger(self):
		"""Send a software trigger command, using SendSWtrigger C API
		"""
		code = libCAENDigitizer.CAEN_DGTZ_SendSWtrigger(
			self._get_handle()
		)
		check_error_code(code)
`

Would be usefull to have it in the official implementation of the library

Also, it would be nice to install this as a pip module

**Comment by SengerM** [comment]
Hello @FraH90 , thank you for your suggestion. Feel free to submit a pull request with your contributions. I am not working anymore with this instrument so I cannot test this. As for the pip installation, you can install the package in any PC with internet access using `pip install git+https://github.com/SengerM/CAENpy`.
